#!/bin/bash

echo "=== Fix New Relic Data Ingestion ==="
echo ""
echo "To see data in New Relic, you need to:"
echo ""
echo "1. Update your .env file:"
echo "   - Set NEW_RELIC_ACCOUNT_ID to your actual account ID"
echo "   - You can find your account ID in the New Relic UI URL or under Account Settings"
echo ""
echo "2. Fix the .env syntax error:"
echo "   - Line 62 has a bash syntax error in PROCESS_EXCLUDE_PATTERN"
echo "   - Change it to: PROCESS_EXCLUDE_PATTERN=\"(kernel|systemd-|ssh-agent|kworker)\""
echo ""
echo "3. Once fixed, restart the collectors:"
echo "   docker-compose -f docker-compose-nr-test.yml down"
echo "   docker-compose -f docker-compose-nr-test.yml up -d"
echo ""
echo "4. Verify data in New Relic with these queries:"
echo ""
echo "   SELECT count(*) FROM Metric WHERE service.name = 'nrdot' SINCE 5 minutes ago"
echo ""
echo "   SELECT uniqueCount(metricName) FROM Metric WHERE service.name = 'nrdot' SINCE 5 minutes ago"
echo ""
echo "   SELECT latest(process.cpu.utilization) FROM Metric "
echo "   WHERE process.executable.name IS NOT NULL "
echo "   SINCE 5 minutes ago FACET process.executable.name"
echo ""
echo "Current Status:"
echo "✅ OTEL Collector is running and receiving metrics"
echo "✅ Metrics Generator is sending data to the collector"
echo "❌ Data is not reaching New Relic due to missing account ID"
echo ""
echo "The collector is working correctly locally - it just needs the account ID to send data to New Relic."