#!/bin/bash

echo "=== NRDOT Data Collection Final Status ==="
echo ""
echo "Account Setup:"
echo "============="
echo "✅ NEW_RELIC_LICENSE_KEY is set"
echo "✅ NEW_RELIC_API_KEY is set"  
echo "✅ NEW_RELIC_ACCOUNT_ID is set to: 33"
echo ""

echo "What's Working:"
echo "=============="
echo "✅ Metrics are properly formatted in OTLP JSON format"
echo "✅ All required metrics are included:"
echo "   - System metrics (CPU, memory utilization)"
echo "   - Process metrics (50 processes with CPU and memory)"
echo "   - NRDOT KPI metrics (optimization score, cost reduction, coverage)"
echo "✅ Metrics transformation is configured"
echo "✅ Resource attributes include service.name=nrdot"
echo ""

echo "Current Issues:"
echo "=============="
echo "⚠️  The main docker-compose.yml has Dockerfile build issues"
echo "⚠️  The .env file has a syntax error on line 62"
echo "   Fix: Change PROCESS_EXCLUDE_PATTERN=(kernel|systemd-|ssh-agent|kworker)"
echo "   To:  PROCESS_EXCLUDE_PATTERN=\"(kernel|systemd-|ssh-agent|kworker)\""
echo ""

echo "To Get Data into New Relic:"
echo "=========================="
echo "1. Fix the .env syntax error"
echo "2. Run a simple collector without Docker build issues:"
echo ""
echo "   docker run -d --name otel-collector \\"
echo "     -e NEW_RELIC_LICENSE_KEY=\${NEW_RELIC_LICENSE_KEY} \\"
echo "     -v \$(pwd)/configs/collector-fixed.yaml:/etc/otel.yaml \\"
echo "     -p 4317:4317 -p 4318:4318 \\"
echo "     otel/opentelemetry-collector-contrib:latest \\"
echo "     --config=/etc/otel.yaml"
echo ""
echo "3. Then run the metrics generator:"
echo "   docker run -d --name metrics-gen \\"
echo "     -v \$(pwd)/scripts:/app \\"
echo "     -w /app \\"
echo "     node:18-alpine \\"
echo "     sh -c 'npm install axios && node metrics-generator-fixed.js'"
echo ""

echo "NRQL Queries Ready to Use:"
echo "========================="
echo "Once data is flowing, use these queries in New Relic:"
echo ""
echo "# All metrics"
echo "SELECT count(*) FROM Metric WHERE service.name = 'nrdot' SINCE 5 minutes ago FACET metricName"
echo ""
echo "# Process metrics" 
echo "SELECT latest(process.cpu.utilization) FROM Metric"
echo "WHERE process.executable.name IS NOT NULL" 
echo "SINCE 5 minutes ago FACET process.executable.name LIMIT 20"
echo ""
echo "# NRDOT KPIs"
echo "SELECT latest(nrdot.optimization.score),"
echo "       latest(nrdot.cost.reduction),"
echo "       latest(nrdot.process.coverage)"
echo "FROM Metric SINCE 5 minutes ago"