# Alternative Deployment for gateway mode (instead of DaemonSet)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nrdot-gateway
  namespace: nrdot-system
  labels:
    app.kubernetes.io/name: nrdot
    app.kubernetes.io/component: gateway
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: nrdot
      app.kubernetes.io/component: gateway
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nrdot
        app.kubernetes.io/component: gateway
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8889"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: nrdot-collector
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
      containers:
        - name: collector
          image: otel/opentelemetry-collector-contrib:0.91.0
          imagePullPolicy: IfNotPresent
          command:
            - /otelcol-contrib
            - --config=/etc/otel/collector-config.yaml
            - --feature-gates=telemetry.useOtelForInternalMetrics
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NEW_RELIC_LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  name: nrdot-license
                  key: license-key
            - name: NEW_RELIC_API_KEY
              valueFrom:
                secretKeyRef:
                  name: nrdot-license
                  key: license-key
            - name: NRDOT_ENVIRONMENT
              value: "production"
            - name: NRDOT_VERSION
              value: "v2.0.0"
            - name: GOMAXPROCS
              value: "2"
          ports:
            - name: otlp-grpc
              containerPort: 4317
              protocol: TCP
            - name: otlp-http
              containerPort: 4318
              protocol: TCP
            - name: metrics
              containerPort: 8888
              protocol: TCP
            - name: prometheus
              containerPort: 8889
              protocol: TCP
            - name: health
              containerPort: 13133
              protocol: TCP
            - name: zpages
              containerPort: 55679
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 13133
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 13133
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: 200m
              memory: 400Mi
            limits:
              cpu: 1000m
              memory: 2Gi
          volumeMounts:
            - name: config
              mountPath: /etc/otel
              readOnly: true
            - name: optimization
              mountPath: /etc/nrdot
              readOnly: true
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
      volumes:
        - name: config
          configMap:
            name: nrdot-config
            items:
              - key: collector-config.yaml
                path: collector-config.yaml
        - name: optimization
          configMap:
            name: nrdot-config
            items:
              - key: optimization.yaml
                path: optimization.yaml
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - nrdot
                    - key: app.kubernetes.io/component
                      operator: In
                      values:
                        - gateway
                topologyKey: kubernetes.io/hostname