# IMPORTANT: This is a template. Do not commit actual license keys to git!
# Use kubectl create secret or external secret management solutions.
apiVersion: v1
kind: Secret
metadata:
  name: nrdot-license
  namespace: nrdot-system
  labels:
    app.kubernetes.io/name: nrdot
    app.kubernetes.io/component: credentials
type: Opaque
stringData:
  # Replace with your actual New Relic license key
  # Option 1: Manual creation
  # kubectl create secret generic nrdot-license -n nrdot-system --from-literal=license-key=YOUR_LICENSE_KEY_HERE
  
  # Option 2: Using this template (not recommended for production)
  license-key: "YOUR_NEW_RELIC_LICENSE_KEY_HERE"
---
# Example: External Secrets Operator configuration
# Uncomment and configure if using External Secrets
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: nrdot-license
#   namespace: nrdot-system
# spec:
#   refreshInterval: 1h
#   secretStoreRef:
#     name: vault-backend
#     kind: SecretStore
#   target:
#     name: nrdot-license
#     creationPolicy: Owner
#   data:
#     - secretKey: license-key
#       remoteRef:
#         key: secret/data/newrelic
#         property: license-key