apiVersion: v1
kind: Service
metadata:
  name: nrdot-metrics
  namespace: nrdot-system
  labels:
    app.kubernetes.io/name: nrdot
    app.kubernetes.io/component: metrics
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 8888
      targetPort: 8888
      protocol: TCP
    - name: prometheus
      port: 8889
      targetPort: 8889
      protocol: TCP
    - name: health
      port: 13133
      targetPort: 13133
      protocol: TCP
    - name: zpages
      port: 55679
      targetPort: 55679
      protocol: TCP
  selector:
    app.kubernetes.io/name: nrdot
    app.kubernetes.io/component: collector
---
apiVersion: v1
kind: Service
metadata:
  name: nrdot-otlp
  namespace: nrdot-system
  labels:
    app.kubernetes.io/name: nrdot
    app.kubernetes.io/component: otlp
spec:
  type: ClusterIP
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
      protocol: TCP
    - name: otlp-http
      port: 4318
      targetPort: 4318
      protocol: TCP
  selector:
    app.kubernetes.io/name: nrdot
    app.kubernetes.io/component: collector