apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dashbuilder

resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
  - redis.yaml

images:
  - name: ghcr.io/deepaksharma/dashbuilder/frontend
    newTag: latest
  - name: ghcr.io/deepaksharma/dashbuilder/backend
    newTag: latest

commonLabels:
  app.kubernetes.io/name: dashbuilder
  app.kubernetes.io/instance: production
  app.kubernetes.io/version: v1.0.0
  app.kubernetes.io/managed-by: kustomize

patches:
  - target:
      kind: Deployment
      name: dashbuilder-frontend
    patch: |-
      - op: add
        path: /spec/template/metadata/annotations
        value:
          prometheus.io/scrape: "true"
          prometheus.io/port: "80"
          prometheus.io/path: "/metrics"
  - target:
      kind: Deployment
      name: dashbuilder-backend
    patch: |-
      - op: add
        path: /spec/template/metadata/annotations
        value:
          prometheus.io/scrape: "true"
          prometheus.io/port: "3000"
          prometheus.io/path: "/metrics"