# This is a template for the secret manifest
# Create actual secret with:
# kubectl create secret generic dashbuilder-secrets \
#   --from-literal=new-relic-api-key=YOUR_API_KEY \
#   --from-literal=new-relic-license-key=YOUR_LICENSE_KEY \
#   -n dashbuilder
#
# Or use this template:
apiVersion: v1
kind: Secret
metadata:
  name: dashbuilder-secrets
  namespace: dashbuilder
type: Opaque
stringData:
  new-relic-api-key: "YOUR_NEW_RELIC_API_KEY"
  new-relic-license-key: "YOUR_NEW_RELIC_LICENSE_KEY"