extensions:
  health_check:

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

  hostmetrics:
    collection_interval: 60s  # Reduced frequency (conservative)
    root_path: /hostfs
    scrapers:
      cpu:
      disk:
      filesystem:
      memory:
      network:
      load:
      paging:

processors:
  batch:
    timeout: 10s  # Larger batches
    send_batch_size: 2000

  memory_limiter:
    check_interval: 1s
    limit_mib: 512

  resource:
    attributes:
      - key: service.name
        value: nrdot-collector-conservative
        action: insert
      - key: optimization.profile
        value: conservative
        action: insert

  resourcedetection:
    detectors: ["system", "env"]
    system:
      hostname_sources: ["os"]

exporters:
  otlphttp:
    endpoint: https://otlp.nr-data.net
    headers:
      api-key: ${NEW_RELIC_LICENSE_KEY}
    compression: gzip

  prometheus:
    endpoint: 0.0.0.0:8889

  debug:
    verbosity: detailed
    sampling_initial: 5
    sampling_thereafter: 200

service:
  pipelines:
    metrics:
      receivers: [otlp, hostmetrics]
      processors: [memory_limiter, batch, resource, resourcedetection]
      exporters: [otlphttp, prometheus, debug]

  telemetry:
    logs:
      level: info

  extensions: [health_check]