#cloud-config
hostname: ${hostname}
manage_etc_hosts: true

packages:
  - nginx
  - python3
  - python3-pip

runcmd:
  - systemctl start nginx
  - systemctl enable nginx
  - echo "<h1>Hello from ${hostname}</h1>" > /var/www/html/index.html