# Base OpenTelemetry Collector Configuration
# This is the base configuration for all profiles
# Use with profile overlays for specific deployments

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
    path: /health
  
  pprof:
    endpoint: 0.0.0.0:1777
    block_profile_fraction: 0
    mutex_profile_fraction: 0
  
  zpages:
    endpoint: 0.0.0.0:55679

receivers:
  # Host Metrics - System level metrics from the host
  hostmetrics:
    collection_interval: 60s
    scrapers:
      cpu:
        metrics:
          system.cpu.utilization:
            enabled: true
      disk:
      filesystem:
      memory:
      network:
      paging:
      processes:
  
  # OTLP Receiver - Receives data via OTLP protocol
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  # Batch processor - Batches data before sending to exporters
  batch:
    timeout: 10s
    send_batch_size: 1000
    send_batch_max_size: 2000
  
  # Resource processor - Adds or modifies resource attributes
  resource:
    attributes:
      - key: service.name
        value: nrdot
        action: insert
      - key: service.version
        value: "2.0.0"
        action: insert
      - key: deployment.environment
        value: ${DEPLOYMENT_ENVIRONMENT:-production}
        action: insert

  # Memory limiter - Prevents out of memory situations
  memory_limiter:
    check_interval: 5s
    limit_percentage: 80
    spike_limit_percentage: 15
  
exporters:
  # New Relic exporter via OTLP
  otlp:
    endpoint: ${NEW_RELIC_OTLP_ENDPOINT:-otlp.nr-data.net:4317}
    headers:
      api-key: ${NEW_RELIC_LICENSE_KEY}
    compression: gzip
    sending_queue:
      enabled: true
      num_consumers: 4
      queue_size: 1000
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 5m
  
  # Prometheus exporter for local monitoring
  prometheus:
    endpoint: 0.0.0.0:8888
    namespace: nrdot
    send_timestamps: true
    metric_expiration: 180m
    enable_open_metrics: true

service:
  pipelines:
    metrics:
      receivers: [hostmetrics, otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [otlp, prometheus]
  
  extensions: [health_check, pprof, zpages]
  
  telemetry:
    logs:
      level: ${LOG_LEVEL:-info}
    metrics:
      level: detailed
      address: 0.0.0.0:8888
