# OpenTelemetry Collector Configuration for New Relic

receivers:
  # Host metrics
  hostmetrics:
    collection_interval: 15s
    scrapers:
      cpu:
      memory:
      process:

  # OTLP receiver for external metrics
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  # Batch processor
  batch:
    timeout: 10s
    send_batch_size: 1000

  # Memory limiter
  memory_limiter:
    check_interval: 1s
    limit_mib: 512

  # Add resource attributes
  attributes:
    actions:
      - key: service.name
        value: nrdot
        action: upsert

exporters:
  # New Relic OTLP exporter
  otlp:
    endpoint: "otlp.nr-data.net:4317"
    headers:
      "api-key": ${NEW_RELIC_LICENSE_KEY}
    compression: gzip
    tls:
      insecure: false

  # Debug exporter
  debug:
    verbosity: normal

extensions:
  health_check:
    endpoint: 0.0.0.0:13133

service:
  telemetry:
    logs:
      level: info
      
  extensions: [health_check]
  
  pipelines:
    metrics:
      receivers: [hostmetrics, otlp]
      processors: [memory_limiter, batch, attributes]
      exporters: [otlp, debug]