global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['nrdot-complete:8888']
    metrics_path: '/metrics'
    
  - job_name: 'otel-collector-dedicated'
    static_configs:
      - targets: ['nrdot-otel:8888']
    metrics_path: '/metrics'
