services:
  # DashBuilder main application
  dashbuilder:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dashbuilder-app
    restart: unless-stopped
    environment:
      - NEW_RELIC_API_KEY=${NEW_RELIC_API_KEY}
      - NEW_RELIC_ACCOUNT_ID=${NEW_RELIC_ACCOUNT_ID}
      - NEW_RELIC_REGION=${NEW_RELIC_REGION:-US}
      - NEW_RELIC_INGEST_KEY=${NEW_RELIC_INGEST_KEY}
      - NRDOT_PROFILE=${NRDOT_PROFILE:-Conservative}
      - NRDOT_TARGET_COVERAGE=${NRDOT_TARGET_COVERAGE:-95}
      - NRDOT_COST_REDUCTION_TARGET=${NRDOT_COST_REDUCTION_TARGET:-40}
    volumes:
      - ./configs:/app/configs:ro
      - ./examples:/app/examples:ro
      - ./docker-output:/app/output
    stdin_open: true
    tty: true
    command: ["bash"]

  # Experiment 1: Baseline NRDOT (no optimizations)
  nrdot-baseline:
    build:
      context: .
      dockerfile: Dockerfile.otel
    container_name: nrdot-baseline
    restart: unless-stopped
    environment:
      - NEW_RELIC_API_KEY=${NEW_RELIC_API_KEY}
      - NEW_RELIC_OTLP_ENDPOINT=https://otlp.nr-data.net:4317
      - EXPERIMENT_NAME=baseline
      - NRDOT_PROFILE=baseline
      - CONFIG_FILE=/etc/nrdot-collector/collector-baseline.yaml
    volumes:
      - ./configs:/etc/nrdot-collector:ro
      - ./logs/baseline:/var/log/nrdot
    ports:
      - "8881:8888"    # Metrics endpoint
      - "13133:13133"  # Health check

  # Experiment 2: Optimized NRDOT (production config)
  nrdot-optimized:
    build:
      context: .
      dockerfile: Dockerfile.otel
    container_name: nrdot-optimized
    restart: unless-stopped
    environment:
      - NEW_RELIC_API_KEY=${NEW_RELIC_API_KEY}
      - NEW_RELIC_OTLP_ENDPOINT=https://otlp.nr-data.net:4317
      - EXPERIMENT_NAME=optimized
      - NRDOT_PROFILE=production
      - CONFIG_FILE=/etc/nrdot-collector/collector-config-production.yaml
    volumes:
      - ./configs:/etc/nrdot-collector:ro
      - ./logs/optimized:/var/log/nrdot
    ports:
      - "8882:8888"    # Metrics endpoint
      - "13134:13133"  # Health check

  # Experiment 3: Conservative NRDOT (moderate optimization)
  nrdot-conservative:
    build:
      context: .
      dockerfile: Dockerfile.otel
    container_name: nrdot-conservative
    restart: unless-stopped
    environment:
      - NEW_RELIC_API_KEY=${NEW_RELIC_API_KEY}
      - NEW_RELIC_OTLP_ENDPOINT=https://otlp.nr-data.net:4317
      - EXPERIMENT_NAME=conservative
      - NRDOT_PROFILE=conservative
      - CONFIG_FILE=/etc/nrdot-collector/collector-conservative.yaml
    volumes:
      - ./configs:/etc/nrdot-collector:ro
      - ./logs/conservative:/var/log/nrdot
    ports:
      - "8883:8888"    # Metrics endpoint
      - "13135:13133"  # Health check
    profiles:
      - experiments

  # Experiment 4: Aggressive NRDOT (maximum optimization)
  nrdot-aggressive:
    build:
      context: .
      dockerfile: Dockerfile.otel
    container_name: nrdot-aggressive
    restart: unless-stopped
    environment:
      - NEW_RELIC_API_KEY=${NEW_RELIC_API_KEY}
      - NEW_RELIC_OTLP_ENDPOINT=https://otlp.nr-data.net:4317
      - EXPERIMENT_NAME=aggressive
      - NRDOT_PROFILE=aggressive
      - CONFIG_FILE=/etc/nrdot-collector/collector-aggressive.yaml
    volumes:
      - ./configs:/etc/nrdot-collector:ro
      - ./logs/aggressive:/var/log/nrdot
    ports:
      - "8884:8888"    # Metrics endpoint
      - "13136:13133"  # Health check
    profiles:
      - experiments

networks:
  default:
    name: nrdot-experiments